import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

// eslint-config-next ships flat config from v16, so it is imported directly.
// Putting it through FlatCompat, which expects the old eslintrc shape, is what
// made `bun run lint` die on a circular structure before it read a single file.
const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "next-env.d.ts",
      // generated by scripts/build-icons.ts, ~400KB of icon data
      "lib/iconBundle.ts",
      "lib/iconBundleSkills.ts",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      // A React 19 advisory about cascading renders, not a correctness rule. Nearly
      // every screen here reads the session out of storage on mount and then sets a
      // flag, which is the exact shape it targets. Rewriting six screens days before
      // submission is the wrong trade, so it stays visible as a warning instead of
      // being silenced file by file.
      "react-hooks/set-state-in-effect": "warn",
      // Fires on performance.now() inside startHold in settings. That function is an
      // event handler, only ever called from onPointerDown and onKeyDown, so it never
      // runs during render. The rule cannot see the call sites.
      "react-hooks/purity": "warn",
    },
  },
];

export default eslintConfig;
