AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 300
    MemorySize: 2048

Resources:
  CalibrateApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.handler
      Runtime: python3.13
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          USER_TABLE: !Ref UserDataTable
      Policies:
        - S3FullAccessPolicy:
            BucketName: calibrate-teamthrow

        - TextractPolicy: {} 

        - DynamoDBCrudPolicy:
            TableName: !Ref UserDataTable

        - Statement:
            - Effect: Allow
              Action:
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
              Resource:
                - !Sub "arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/global.anthropic.claude-sonnet-4-6"
                - "arn:aws:bedrock:*::foundation-model/anthropic.claude-sonnet-4-6*"
                - "arn:aws:bedrock:*::foundation-model/cohere.embed-multilingual-v3"
  UserDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String

Outputs:
  FunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt CalibrateApiFunctionUrl.FunctionUrl
