// Scans the source for "prefix:name" icon literals, pulls their data from the
// Iconify API once, and writes lib/iconBundle.ts. Run it after adding an icon:
//   bun run scripts/build-icons.ts
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOTS = ["app", "components", "lib"];
const ICON_RE = /"([a-z0-9]+(?:-[a-z0-9]+)*):([a-z0-9]+(?:-[a-z0-9]+)*)"/g;
// "md" is the Tailwind breakpoint: conditional classNames put bare "md:flex" strings
// in the source, which look exactly like an icon reference to the regex above.
const NOT_ICONS = new Set(["calibrate", "md", "sm", "lg", "xl"]);

// The technology logos are detailed multi-path artwork and dwarf everything else
// (devicon averages 42KB an icon). They only ever render on the dashboard, so they
// go in their own module and only that page's chunk carries them.
const SKILL_PREFIXES = new Set(["logos", "devicon"]);

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return sourceFiles(path);
    return /\.tsx?$/.test(path) ? [path] : [];
  });
}

const byPrefix = new Map<string, Set<string>>();

for (const root of ROOTS) {
  for (const file of sourceFiles(root)) {
    const source = readFileSync(file, "utf8");
    for (const [, prefix, name] of source.matchAll(ICON_RE)) {
      if (NOT_ICONS.has(prefix)) continue;
      if (!byPrefix.has(prefix)) byPrefix.set(prefix, new Set());
      byPrefix.get(prefix)!.add(name);
    }
  }
}

const prefixes = [...byPrefix.keys()].sort();
const core: string[] = [];
const skills: string[] = [];
const missing: string[] = [];
let count = 0;

for (const prefix of prefixes) {
  const names = [...byPrefix.get(prefix)!].sort();
  const url = `https://api.iconify.design/${prefix}.json?icons=${names.join(",")}`;
  const response = await fetch(url);

  if (!response.ok) {
    missing.push(...names.map((name) => `${prefix}:${name}`));
    continue;
  }

  const data = await response.json();
  const found = Object.keys(data.icons ?? {});

  for (const name of names) {
    if (!found.includes(name) && !(data.aliases ?? {})[name]) {
      missing.push(`${prefix}:${name}`);
    }
  }

  if (!found.length && !Object.keys(data.aliases ?? {}).length) continue;

  count += found.length;
  (SKILL_PREFIXES.has(prefix) ? skills : core).push(JSON.stringify(data));
  console.log(`${prefix}: ${found.length}/${names.length}`);
}

function render(note: string, collections: string[]) {
  return `// Generated by scripts/build-icons.ts. Do not edit by hand.
// ${note}
import { addCollection } from "@iconify/react/offline";

${collections.map((json) => `addCollection(${json});`).join("\n\n")}
`;
}

writeFileSync(
  "lib/iconBundle.ts",
  render(
    "Bundling the icons keeps them out of the network path, so they paint with the\n// first render instead of trickling in from api.iconify.design one set at a time.",
    core
  )
);

writeFileSync(
  "lib/iconBundleSkills.ts",
  render(
    "The technology logos, imported by the dashboard alone so no other route pays for them.",
    skills
  )
);

console.log(`\nbundled ${count} icons: ${core.length} core sets, ${skills.length} skill sets`);
if (missing.length) console.log(`not found: ${missing.join(", ")}`);
