import re

TERMS = {
    "Python": ["python"],
    "Java": ["java"],
    "JavaScript": ["javascript"],
    "TypeScript": ["typescript"],
    "C#": ["c#", "csharp", "c sharp"],
    "C++": ["c++", "cpp"],
    "Golang": ["golang"],
    "Rust": ["rust"],
    "PHP": ["php"],
    "Ruby": ["ruby"],
    "Kotlin": ["kotlin"],
    "Swift": ["swift"],
    "Scala": ["scala"],
    "React": ["react", "reactjs", "react.js"],
    "React Native": ["react native", "react-native"],
    "Angular": ["angular"],
    "Vue": ["vue", "vuejs", "vue.js"],
    "Next.js": ["next.js", "nextjs"],
    ".NET": [".net", "dotnet"],
    "Spring": ["spring boot", "spring"],
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi"],
    "Node.js": ["node.js", "nodejs", "node js"],
    "Laravel": ["laravel"],
    "SQL": ["sql"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MySQL": ["mysql"],
    "MongoDB": ["mongodb", "mongo"],
    "Redis": ["redis"],
    "Elasticsearch": ["elasticsearch", "elastic search"],
    "Kafka": ["kafka"],
    "Spark": ["spark"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "Pandas": ["pandas"],
    "LLM": ["llm", "large language model"],
    "NLP": ["nlp", "natural language processing"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure"],
    "GCP": ["gcp", "google cloud"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Terraform": ["terraform"],
    "Jenkins": ["jenkins"],
    "Ansible": ["ansible"],
    "CI/CD": ["ci/cd", "cicd"],
    "Git": ["git"],
    "Linux": ["linux"],
    "Grafana": ["grafana"],
    "Prometheus": ["prometheus"],
    "Android": ["android"],
    "iOS": ["ios"],
    "Flutter": ["flutter"],
    "Selenium": ["selenium"],
    "Cypress": ["cypress"],
    "JUnit": ["junit"],
    "Postman": ["postman"],
}


def build_pattern(aliases):
    parts = []
    for alias in aliases:
        prefix = r"(?<![A-Za-z0-9_])" if alias[0].isalnum() else ""
        suffix = r"(?![A-Za-z0-9_])" if alias[-1].isalnum() else ""
        parts.append(prefix + re.escape(alias) + suffix)
    return re.compile("|".join(parts), re.IGNORECASE)


PATTERNS = {term: build_pattern(aliases) for term, aliases in TERMS.items()}

SKILL_CATEGORIES = {
    "Python": "computer programming",
    "Java": "computer programming",
    "JavaScript": "computer programming",
    "TypeScript": "computer programming",
    "C#": "computer programming",
    "C++": "computer programming",
    "Golang": "computer programming",
    "Rust": "computer programming",
    "PHP": "computer programming",
    "Ruby": "computer programming",
    "Kotlin": "computer programming",
    "Swift": "computer programming",
    "Scala": "computer programming",
    "React": "software and applications development and analysis",
    "React Native": "software and applications development and analysis",
    "Angular": "software and applications development and analysis",
    "Vue": "software and applications development and analysis",
    "Next.js": "software and applications development and analysis",
    ".NET": "software and applications development and analysis",
    "Spring": "software and applications development and analysis",
    "Django": "software and applications development and analysis",
    "Flask": "software and applications development and analysis",
    "FastAPI": "software and applications development and analysis",
    "Node.js": "software and applications development and analysis",
    "Laravel": "software and applications development and analysis",
    "Android": "software and applications development and analysis",
    "iOS": "software and applications development and analysis",
    "Flutter": "software and applications development and analysis",
    "SQL": "query languages",
    "PostgreSQL": "database management systems",
    "MySQL": "database management systems",
    "MongoDB": "database management systems",
    "Redis": "database management systems",
    "Elasticsearch": "database management systems",
    "Kafka": "data processing",
    "Spark": "data processing",
    "Pandas": "data processing",
    "TensorFlow": "machine learning",
    "PyTorch": "machine learning",
    "scikit-learn": "machine learning",
    "LLM": "machine learning",
    "NLP": "machine learning",
    "AWS": "cloud services",
    "Azure": "cloud services",
    "GCP": "cloud services",
    "Docker": "containerization",
    "Kubernetes": "containerization",
    "Terraform": "infrastructure automation",
    "Ansible": "infrastructure automation",
    "Jenkins": "continuous integration",
    "CI/CD": "continuous integration",
    "Git": "version control",
    "Linux": "operating systems",
    "Grafana": "monitoring",
    "Prometheus": "monitoring",
    "Selenium": "software testing",
    "Cypress": "software testing",
    "JUnit": "software testing",
    "Postman": "software testing",
}