import type { Language } from "@/contexts/LanguageContext";

// Suggestions for the "field of study" box, not a closed list — the field
// stays free text, so anything missing here can still be typed. The two
// arrays are parallel: index n is the same programme in both languages, which
// is what keeps them reviewable side by side when one gets edited.
const STUDY_FIELDS: Record<Language, string[]> = {
  en: [
    "Computer Engineering",
    "Software Engineering",
    "Computer Science",
    "Artificial Intelligence Engineering",
    "Data Science",
    "Management Information Systems",
    "Electrical and Electronics Engineering",
    "Industrial Engineering",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Environmental Engineering",
    "Food Engineering",
    "Biomedical Engineering",
    "Aerospace Engineering",
    "Mathematics",
    "Statistics",
    "Physics",
    "Chemistry",
    "Biology",
    "Molecular Biology and Genetics",
    "Business Administration",
    "Economics",
    "Finance",
    "Accounting",
    "Marketing",
    "Logistics and Supply Chain Management",
    "International Relations",
    "Political Science and Public Administration",
    "Law",
    "Psychology",
    "Sociology",
    "History",
    "Philosophy",
    "Medicine",
    "Dentistry",
    "Pharmacy",
    "Nursing",
    "Architecture",
    "Interior Architecture",
    "Industrial Design",
    "Graphic Design",
    "Visual Communication Design",
    "Communication and Media Studies",
    "English Language and Literature",
    "Translation and Interpreting",
    "Educational Sciences",
    "Tourism Management",
    "Gastronomy and Culinary Arts",
  ],
  tr: [
    "Bilgisayar Mühendisliği",
    "Yazılım Mühendisliği",
    "Bilgisayar Bilimleri",
    "Yapay Zeka Mühendisliği",
    "Veri Bilimi",
    "Yönetim Bilişim Sistemleri",
    "Elektrik-Elektronik Mühendisliği",
    "Endüstri Mühendisliği",
    "Makine Mühendisliği",
    "Mekatronik Mühendisliği",
    "İnşaat Mühendisliği",
    "Kimya Mühendisliği",
    "Çevre Mühendisliği",
    "Gıda Mühendisliği",
    "Biyomedikal Mühendisliği",
    "Uçak ve Uzay Mühendisliği",
    "Matematik",
    "İstatistik",
    "Fizik",
    "Kimya",
    "Biyoloji",
    "Moleküler Biyoloji ve Genetik",
    "İşletme",
    "Ekonomi",
    "Finans",
    "Muhasebe",
    "Pazarlama",
    "Lojistik ve Tedarik Zinciri Yönetimi",
    "Uluslararası İlişkiler",
    "Siyaset Bilimi ve Kamu Yönetimi",
    "Hukuk",
    "Psikoloji",
    "Sosyoloji",
    "Tarih",
    "Felsefe",
    "Tıp",
    "Diş Hekimliği",
    "Eczacılık",
    "Hemşirelik",
    "Mimarlık",
    "İç Mimarlık",
    "Endüstriyel Tasarım",
    "Grafik Tasarım",
    "Görsel İletişim Tasarımı",
    "İletişim ve Medya Çalışmaları",
    "İngiliz Dili ve Edebiyatı",
    "Mütercim-Tercümanlık",
    "Eğitim Bilimleri",
    "Turizm İşletmeciliği",
    "Gastronomi ve Mutfak Sanatları",
  ],
};

/** Field-of-study suggestions in the language the user is reading the app in. */
export function studyFieldSuggestions(language: Language): string[] {
  return STUDY_FIELDS[language];
}
